spring:
  application:
    name: "traders"
  datasource:
    url: jdbc:mariadb://localhost:3306/winds_traders
    username: root
    password: admin
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  sql:
    init:
      mode: never

server:
  port: 9090